#define RAGE_RB_PROC_ERROR "You can only pass instances of Proc object as an argument."
#define RAGE_RB_INCOMPATIBLE "This game may be incompatible with this version of RAGE.\n\n"
#define RAGE_RB_SCRIPT_ERROR "Script Error!\n\t%s: %s\n"
#define RAGE_RB_FILE_MISSING_ERROR "File '%s' not found."
#define RAGE_RB_PATH_MISSING_ERROR "Path '%s' not found."
#define RAGE_EVENT_ERROR "Cannot call methods from abstract RAGE::Event class."
#define RAGE_BITMAP_ERROR "Width and Height values need to be Fixnum."
#define RAGE_BITMAP_PARENT_ERROR "Parent argument must be an instance of RAGE::Bitmap."
#define RAGE_BITMAP_NOT_CREATED_ERROR "Cannot set nil bitmap as drawing target. Create or load a bitmap first."
#define RAGE_COLOR_ERROR "Argument must be an instance of RAGE::Color class."
#define RAGE_FONT_ERROR "Argument must be an instance of RAGE::Font class."

#define RAGE_ERROR_MUSIC_LOAD_FAIL "Music file '%s' failed to load."
#define RAGE_ERROR_SFX_LOAD_FAIL "Sfx file '%s' failed to load."
#define RAGE_ERROR_EVENT_QUEUE_FAIL "Failed to initialize event queue."
#define RAGE_ERROR_TIMER_FAIL "Failed to initialize timer."
#define RAGE_ERROR_INI_CREATE_FAIL "IniFile creation failed."
#define RAGE_ERROR_INI_LOAD_FAIL "IniFile failed load file '%s'."
#define RAGE_ERROR_BITMAP_CREATE_FAIL "Bitmap creation failed."
#define RAGE_ERROR_SUBBITMAP_CREATE_FAIL "Sub-Bitmap creation failed."
#define RAGE_ERROR_BITMAP_LOAD_FAIL "Bitmap failed to load file '%s'."
#define RAGE_ERROR_FONT_LOAD_FAIL "Font failed to load file '%s'."
#define RAGE_ERROR_MOUSE_CURSOR_CREATE_FAIL "Failed to create bitmap mouse cursor."
#define RAGE_ERROR_SHADER_CODE_NOT_ADDED "Shader code is not added, cannot set it as active."
#define RAGE_SHADER_COMPILE_LINK_ERROR "Shader Error:\n"
#define RAGE_ERROR_NO_EXT_FRAGMENT_SHADERS "Your OpenGL implementation does not support fragment shaders."
#define RAGE_ERROR_CANNOT_CREATE_VOICE "RAGE Error: Failed to allocate audio voice. Audio functions will not work.\n"
#define RAGE_ERROR_CANNOT_CREATE_MIXER "RAGE Error: Failed to allocate audio mixer. Audio functions will not work.\n"